services:
  app_my_mysql:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.my_mysql
    environment:
      FULLY_QUALIFY_NAMES: $APP_MY_MYSQL_FULLY_QUALIFY_NAMES
      HASURA_SERVICE_TOKEN_SECRET: $APP_MY_MYSQL_HASURA_SERVICE_TOKEN_SECRET
      JDBC_URL: $APP_MY_MYSQL_JDBC_URL
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_MY_MYSQL_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_MY_MYSQL_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 7618:8080
